<a href="https://colab.research.google.com/github/victorbahlangene/Fastai-Docs/blob/main/Model_hooks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nbdev

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.8/64.8 kB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.7/58.7 kB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.1/82.1 kB 4.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 8.0 MB/s eta 0:00:00


In [2]:
!pip install -Uqq fastbook

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 719.8/719.8 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 24.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.6/519.6 kB 31.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 20.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 14.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 26.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 43.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 47.7 MB/s eta 0:00:00


# Model hooks
Callback and helper function to add hooks in models

In [3]:
from fastai.test_utils import *

## What are hooks

In [4]:
import torch
import torch.nn as nn

Forward hooks are functions that take three arguments: **the layer it’s applied to, the input of that layer and the output of that layer**.

In [5]:
tst_model = nn.Linear(5,3)

def example_forward_hook(m,i,o): print(m,i,o)

x = torch.randn(4,5)
hook = tst_model.register_forward_hook(example_forward_hook)
y = tst_model(x)
hook.remove()

Linear(in_features=5, out_features=3, bias=True) (tensor([[-0.1960, -0.7425,  0.4338,  1.1581, -0.7060],
        [-1.0166,  0.6263,  0.5599,  0.4935, -0.4149],
        [ 0.4090,  0.3788,  0.9381,  0.5656,  0.0719],
        [ 0.3580, -0.1364, -0.1676,  0.9226, -0.9239]]),) tensor([[-0.8899, -0.4858, -0.5871],
        [-0.2556,  0.0226, -0.4437],
        [ 0.0087, -0.0489, -1.1091],
        [-0.8057, -0.2550, -0.6010]], grad_fn=<AddmmBackward0>)


In [6]:
tst_model = nn.Linear(5,3)

def example_forward_hook(m,i,o): print(m)

x = torch.randn(4,5)
hook = tst_model.register_forward_hook(example_forward_hook)
y = tst_model(x)
hook.remove()

Linear(in_features=5, out_features=3, bias=True)


In [7]:
tst_model = nn.Linear(5,3)

def example_forward_hook(m,i,o): print(i,i[0].shape)

x = torch.randn(4,5)
hook = tst_model.register_forward_hook(example_forward_hook)
y = tst_model(x)
hook.remove()

(tensor([[ 0.5443, -0.9213,  2.4496,  0.9330, -0.3271],
        [-1.1699,  2.0541, -0.1535,  0.8731,  0.7136],
        [-1.1722,  1.5937, -0.2732,  0.5370, -0.1316],
        [ 2.4264, -0.3225,  0.8017, -0.7404, -1.4495]]),) torch.Size([4, 5])


In [8]:
tst_model = nn.Linear(5,3)

def example_forward_hook(m,i,o): print(o)

x = torch.randn(4,5)
hook = tst_model.register_forward_hook(example_forward_hook)
y = tst_model(x)
hook.remove()

tensor([[-0.2836, -0.1895,  0.9892],
        [ 0.2430,  0.1717, -0.3140],
        [ 0.0885, -0.0724, -0.6834],
        [ 0.3885,  0.9768, -0.3817]], grad_fn=<AddmmBackward0>)


## Hook method

In [9]:
import fastbook
from fastbook import *

In [10]:
Hook

fastai.callback.hook.Hook

In [11]:
tst_model = nn.Linear(5,3)
hook = Hook(tst_model, lambda m,i,o: print(o))
y = tst_model(x)

tensor([[-0.6625,  0.7216, -0.5922],
        [ 0.2128,  0.0497, -0.5045],
        [-0.1155,  0.2259, -0.1747],
        [-0.3244, -0.8833, -0.4930]])


In [12]:
y

tensor([[-0.6625,  0.7216, -0.5922],
        [ 0.2128,  0.0497, -0.5045],
        [-0.1155,  0.2259, -0.1747],
        [-0.3244, -0.8833, -0.4930]], grad_fn=<AddmmBackward0>)

In [13]:
tst_model = nn.Linear(5,3)
def test2_hook(m,i,o): print(i,o)
hook = Hook(tst_model, test2_hook)
y = tst_model(x)

(tensor([[-0.2400, -1.8547, -0.8561,  0.0544, -0.6039],
        [-0.1092,  0.8768, -0.9688, -0.5511, -1.1505],
        [-1.3190,  1.2971,  0.7561, -0.0980, -0.3736],
        [-1.7620,  0.8441, -1.2029,  0.2453,  2.0300]]),) tensor([[ 0.1963,  0.7703,  0.5106],
        [ 0.6347,  0.0916, -0.6947],
        [ 0.4149, -1.0374, -0.1387],
        [ 0.4048, -1.2948, -0.0490]])


## Hooks

In [14]:
Hooks

fastai.callback.hook.Hooks

Create several hooks on the modules in ms with hook_func.

In [15]:
layers = [nn.Linear(5,10), nn.ReLU(), nn.Linear(10,3)]
tst_model = nn.Sequential(*layers)
hooks = Hooks(tst_model, lambda m,i,o: print(o[0].shape))
y = tst_model(x)
hooks.remove()

torch.Size([10])
torch.Size([10])
torch.Size([3])


In [16]:
hooks

In [17]:
hooks.stored

(#3) [None,None,None]

In [18]:
layers[0](x)

tensor([[-0.5531, -0.8771, -0.3780,  0.3950, -0.2589, -0.1010,  0.6401, -0.0268, -0.5655, -0.3721],
        [ 0.4572, -0.4736,  0.2558, -0.7852, -0.1241,  0.2211, -0.0637,  1.6697, -0.2269,  0.1502],
        [ 0.6385,  0.4062, -0.0986,  0.1149,  0.1831,  0.3724, -0.8923,  0.5607,  0.4784,  0.3475],
        [ 0.5885, -0.7887, -1.8518,  0.1175, -0.6030,  0.5700,  0.4612,  0.0295, -0.2116,  0.5673]], grad_fn=<AddmmBackward0>)

In [19]:
layers = [nn.Linear(5,10), nn.ReLU(), nn.Linear(10,3)]
tst_model = nn.Sequential(*layers)
hooks = Hooks(tst_model, lambda m,i,o: o)
y = tst_model(x)
test_eq(hooks.stored[0], layers[0](x))
test_eq(hooks.stored[1], F.relu(layers[0](x)))
test_eq(hooks.stored[2], y)
hooks.remove()

In [20]:
layers = [nn.Linear(5,10), nn.ReLU(), nn.Linear(10,3)]
tst_model = nn.Sequential(*layers)
hooks = Hooks(tst_model, lambda m,i,o: print(o))
y = tst_model(x)
print("\n")
print(hooks.stored[0])

hooks.remove()

tensor([[ 0.6852,  1.0306, -0.5184,  1.1874,  0.3606,  0.2654,  0.6110, -0.7365,  0.1323,  0.5231],
        [ 0.0975,  0.2875,  0.4452,  0.1526,  0.0053,  0.1568,  0.1449, -0.1921, -0.6417,  0.3963],
        [-0.0627, -0.7076,  0.7955, -0.4060, -0.5042,  0.0779, -0.0853,  0.5074, -0.6921, -0.5346],
        [ 1.8567,  0.9030,  0.0993,  0.2727, -0.9985, -1.3063,  0.7712, -0.5689, -1.0713, -0.7483]])
tensor([[0.6852, 1.0306, 0.0000, 1.1874, 0.3606, 0.2654, 0.6110, 0.0000, 0.1323, 0.5231],
        [0.0975, 0.2875, 0.4452, 0.1526, 0.0053, 0.1568, 0.1449, 0.0000, 0.0000, 0.3963],
        [0.0000, 0.0000, 0.7955, 0.0000, 0.0000, 0.0779, 0.0000, 0.5074, 0.0000, 0.0000],
        [1.8567, 0.9030, 0.0993, 0.2727, 0.0000, 0.0000, 0.7712, 0.0000, 0.0000, 0.0000]])
tensor([[-0.5224, -0.7714,  0.4092],
        [-0.3680, -0.0118,  0.2262],
        [-0.3818,  0.1652,  0.1150],
        [-0.3017, -0.7995, -0.0766]])


None


In [21]:
layers = [nn.Linear(5,10), nn.ReLU(), nn.Linear(10,3)]
tst_model = nn.Sequential(*layers)
hooks = Hooks(tst_model, lambda m,i,o: o)
y = tst_model(x)
print("\n")
print(hooks.stored[0])

hooks.remove()



tensor([[-0.9226,  0.2338,  0.7396, -0.4916,  0.0244,  1.0041, -0.3825, -0.7541, -0.8064,  0.4093],
        [-0.1471, -0.0801,  0.1770, -0.1136, -0.0418,  1.1746,  0.9130, -0.0155, -0.1300, -0.3831],
        [ 0.6381,  0.7126, -0.5211, -1.0238,  0.5759,  0.3246,  0.9597,  0.2932,  0.0763, -0.8201],
        [-0.2140, -0.3583,  0.2565, -0.1135,  0.1397, -0.1719,  1.4508, -1.5187,  0.9513,  0.6423]])


In [22]:
hooks.stored

(#3) [tensor([[-0.9226,  0.2338,  0.7396, -0.4916,  0.0244,  1.0041, -0.3825, -0.7541, -0.8064,  0.4093],
        [-0.1471, -0.0801,  0.1770, -0.1136, -0.0418,  1.1746,  0.9130, -0.0155, -0.1300, -0.3831],
        [ 0.6381,  0.7126, -0.5211, -1.0238,  0.5759,  0.3246,  0.9597,  0.2932,  0.0763, -0.8201],
        [-0.2140, -0.3583,  0.2565, -0.1135,  0.1397, -0.1719,  1.4508, -1.5187,  0.9513,  0.6423]]),tensor([[0.0000, 0.2338, 0.7396, 0.0000, 0.0244, 1.0041, 0.0000, 0.0000, 0.0000, 0.4093],
        [0.0000, 0.0000, 0.1770, 0.0000, 0.0000, 1.1746, 0.9130, 0.0000, 0.0000, 0.0000],
        [0.6381, 0.7126, 0.0000, 0.0000, 0.5759, 0.3246, 0.9597, 0.2932, 0.0763, 0.0000],
        [0.0000, 0.0000, 0.2565, 0.0000, 0.1397, 0.0000, 1.4508, 0.0000, 0.9513, 0.6423]]),tensor([[ 0.0614, -0.4749, -0.3101],
        [-0.2112, -0.5151, -0.0540],
        [-0.6004, -0.4172, -0.3468],
        [-0.3489, -0.3165,  0.1106]])]

## HookCallback

```python
 HookCallback (modules=None, every=None, remove_end=True, is_forward=True,
               detach=True, cpu=True, include_paramless=False, hook=None)
```

In [23]:
synth_learner

<function fastai.test_utils.synth_learner(n_trn=10, n_val=2, cuda=False, lr=0.001, data=None, model=None, *, loss_func: 'callable | None' = None, opt_func: 'Optimizer | OptimWrapper' = <function Adam at 0x7e37cca0b760>, splitter: 'callable' = <function trainable_params at 0x7e37cfc50e50>, cbs: 'Callback | MutableSequence | None' = None, metrics: 'callable | MutableSequence | None' = None, path: 'str | Path | None' = None, model_dir: 'str | Path' = 'models', wd: 'float | int | None' = None, wd_bn_bias: 'bool' = False, train_bn: 'bool' = True, moms: 'tuple' = (0.95, 0.85, 0.95), default_cbs: 'bool' = True)>

In [24]:
class TstCallback(HookCallback):
  def hook(self, m,i,o): return o
  def after_batch(self): test_eq(self.hooks.stored[0], self.pred)

learn = synth_learner(n_trn=5, cbs = TstCallback())
learn.fit(1)

/usr/local/lib/python3.10/dist-packages/fastai/callback/core.py:69: UserWarning: You are shadowing an attribute (modules) that exists in the learner. Use `self.learn.modules` to avoid this
  warn(f"You are shadowing an attribute ({name}) that exists in the learner. Use `self.learn.{name}` to avoid this")


In [25]:
class TstCallback(HookCallback):
    def __init__(self, modules=None, remove_end=True, detach=True, cpu=False):
        super().__init__(modules, None, remove_end, False, detach, cpu)
    def hook(self, m, i, o): return o
    def after_batch(self):
        if self.training:
            test_eq(self.hooks.stored[0][0], 2*(self.pred-self.y)/self.pred.shape[0])

learn = synth_learner(n_trn=5, cbs = TstCallback())
learn.fit(1)

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py:1344: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "


In [26]:
doc(synth_learner)

In [29]:
# class TstCallback(HookCallback):
#     def __init__(self, modules=None, remove_end=True, detach=True, cpu=False):
#         super().__init__(modules, None, remove_end, False, detach, cpu)
#     def hook(self, m, i, o): return o
#     def after_batch(self):
#         if self.training:
#             test_eq(self.hooks.stored[0][0], 2*(self.pred-self.y)/self.pred.shape[0])

# layers = [nn.Linear(5,10), nn.ReLU(), nn.Linear(10,3)]
# tst_model = nn.Sequential(*layers)

# learn = synth_learner(n_trn=5, model=tst_model, cbs = TstCallback())
# learn.fit(1)

using a dataset

In [30]:
doc(ActivationStats)